### PR TITLE
 Add the ability to set reconnection attempts 

### PR DESCRIPTION
**Pull request by ivolnistov**
Optional: add in top of config.yml `reconnectionAttempts`, possible values is `integer` or `Infinity` `default`: 10 attempts

### CODE REVIEW

**Comment by plouc** [comment]
@ivolnistov, it's a good idea, some people already asked for infinite retries, but I think we should add the ability to also customize the delay, what do you think?

**Comment by ivolnistov** [comment]
Dunno, reconnectionAttempts was critical for me, because I have many TVs on different floors, and when I update the image of the dockers, all of them end up trying to reconnect.I think 10sec good timeout for reconnection interval, but someone may have another opinion )

**Comment by plouc** [comment]
I see, let's stick with your actual need, and if someone needs further customization, we'll see :)

**Comment by plouc** [comment]
I'll let you know when I publish a new release of `@mozaik/ui`

**Comment by plouc** [comment]
And of course, thank you for your contribution!

**Pull request merged**
